modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/ChAoSUnItY/EkiLib/issues/"

[[mods]]
modId="eki_lib"
version="1.0.20"
displayName="Eki Lib"
displayURL="https://github.com/ChAoSUnItY/EkiLib/"
logoFile="Eki_Lib_Logo.png"
credits=""
authors="ChAoS_UnItY"
description='''A new generation of station system library in Minecraft!'''