modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/ChAoSUnItY/EkiLib/issues"

[[mods]]
modId="eki_lib"
version="1.0.15"
displayName="Eki Lib"
updateJSONURL="https://raw.githubusercontent.com/ChAoSUnItY/EkiLib/1.16.3/src/main/resources/update.json"
displayURL="https://github.com/ChAoSUnItY/EkiLib"
logoFile="Eki_Lib_Logo.png"
credits=""
authors="ChAoS_UnItY"
description='''A new generation of station system library in Minecraft!'''