modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ChAoSUnItY/EkiLib/issues"

[[mods]]
modId="eki_lib"
version="1.16.3-1.0.0"
displayName="Eki Lib"
updateJSONURL="http://example.com/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits=""
authors="ChAoS_UnItY"
description='''A new generation of station system library in Minecraft!'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
